version: '2'

services:
  postgres:
    image: justdevzero/postgresql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'template1'
    volumes:
      - 'postgresql:/var/lib/postgresql'
    ports:
      - '5432:5432'
volumes:
  postgresql:
